name: Deploy to Unikraft Cloud

on:
  push:
    branches: [ "main" ] # 对应你的默认分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Unikraft CLI (KraftKit)
        uses: unikraft/setup-action@v1

      - name: Run on Unikraft Cloud
        env:
          UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
        run: |
          # 显式将 kraft 路径加入环境变量并运行
          export PATH="$HOME/.local/bin:$PATH"
          kraft run \
            --metro fra \
            --publish 443:8080/http+tls \
            --scale-to-zero policy=on,cooldown-time=1000 \
            --image ghcr.io/huangshelvey/uni:latest
