name: Deploy to Unikraft Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install KraftKit
        run: curl --proto '=https' --tlsv1.2 -sSf https://kraftkit.sh | sh

      - name: Run on Unikraft Cloud
        env:
          UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
        run: /home/runner/.local/bin/kraft run --metro fra --publish 443:8080/http+tls --scale-to-zero policy=on,cooldown-time=1000 --image ghcr.io/huangshelvey/uni:latest
